#!/usr/bin/env python3
"""communities.py — clusters DISCOVERED, not declared (L1 evidence + graph colors).

Functional brain networks aren't hand-drawn — they emerge from connectivity.
This runs label propagation (deterministic order, seeded per-node) over the
REAL edge set: explicit [[links]] between memory nodes + strong PMI pairs from
coactivation. Communities >= 2 members get stable colors in .obsidian/graph.json
(named by their highest-degree hub) and an evidence file the brain reads
(Atlas/AI/Brain/communities.md). Replaces the hand-coded cluster queries —
if the graph's real structure changes, the colors follow the data.
"""
import json, re, unicodedata
from collections import Counter, defaultdict
from pathlib import Path

V = Path.home() / "Projects/2ndm1nd"
ENTITY_DIRS = ["Atlas/Projects", "Atlas/Organizations", "Atlas/People",
               "Atlas/Memory/topics", "Atlas/Ideas", "Atlas/Mind", "Atlas/Context"]
OUT = V / "Atlas/AI/Brain/communities.md"
PALETTE = [0xE0803A, 0xC0504D, 0x8064A2, 0x4BACC6, 0x9BBB59, 0x4F81BD, 0xD9B037, 0x7F7F7F]


def fold(s):
    return "".join(c for c in unicodedata.normalize("NFKD", s.casefold())
                   if not unicodedata.combining(c))


def aliases(text):
    if not text.startswith("---"):
        return []
    end = text.find("\n---", 3)
    if end < 0:
        return []
    fm, out = text[3:end], []
    m = re.search(r"^aliases:\s*\[(.*?)\]\s*$", fm, re.M)
    if m:
        out += [a.strip().strip("'\"") for a in m.group(1).split(",")]
    m = re.search(r"^aliases:\s*$(.*?)(?=^\w[\w-]*:|^---|\Z)", fm, re.M | re.S)
    if m:
        out += [x.group(1).strip().strip("'\"") for x in re.finditer(r"^\s*-\s*(.+)$", m.group(1), re.M)]
    return [a for a in out if a]


nodes, idx = {}, {}
for d in ENTITY_DIRS:
    base = V / d
    if not base.is_dir():
        continue
    for p in sorted(base.glob("*.md")):
        if p.name == "README.md" or p.stem.casefold() in {"ontology", "moc"}:
            continue
        t = p.read_text(encoding="utf-8", errors="replace")
        m = re.search(r"^alias-of:\s*\"?(?:\[\[)?([^\]\"\n]+)", t[:800], re.M)
        target = m.group(1).strip() if m else p.stem
        if target == p.stem:
            nodes[p.stem] = t
        for a in {p.stem} | set(aliases(t)):
            idx.setdefault(fold(a), target)   # persona terms map to their target

edges = Counter()
for stem, t in nodes.items():
    body = t.split("\n---", 2)[-1]
    for L in re.findall(r"\[\[([^\]|#]+)", body):
        tgt = idx.get(fold(L.strip().split("/")[-1]))
        if tgt and tgt != stem:
            edges[tuple(sorted((stem, tgt)))] += 1
co = V / "Atlas/AI/Brain/coactivation.md"
if co.exists():
    for a, b, s in re.findall(r"\*\*(.+?)\*\* ↔ \*\*(.+?)\*\* — npmi ([\d.]+)", co.read_text()):
        if float(s) >= 0.5 and a in nodes and b in nodes:
            edges[tuple(sorted((a, b)))] += 1

adj = defaultdict(set)
for (a, b), _n in edges.items():
    adj[a].add(b); adj[b].add(a)

# deterministic label propagation
label = {n: n for n in sorted(nodes)}
for _round in range(12):
    changed = 0
    for n in sorted(adj):
        counts = Counter(label[m] for m in adj[n])
        if not counts:
            continue
        best = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[0][0]
        if label[n] != best:
            label[n] = best; changed += 1
    if not changed:
        break

groups = defaultdict(list)
for n, l in label.items():
    if n in adj:
        groups[l].append(n)
comms = [sorted(m) for m in groups.values() if len(m) >= 2]
deg = {n: len(adj[n]) for n in adj}
comms.sort(key=len, reverse=True)

# write graph colors (auto-derived)
gj = V / ".obsidian/graph.json"
d = json.loads(gj.read_text()) if gj.exists() else {}
d["colorGroups"] = []
for i, mem in enumerate(comms[:8]):
    q = " OR ".join(f'file:"{m}"' for m in mem)
    d["colorGroups"].append({"query": q, "color": {"a": 1, "rgb": PALETTE[i % len(PALETTE)]}})
gj.write_text(json.dumps(d, indent=2))

body = ["---", "title: communities", "type: note", "---", "",
        f"# COMMUNITIES — clusters discovered from real connectivity (L1; {len(nodes)} nodes, "
        f"{len(edges)} edges incl. PMI>=0.5; label propagation; regenerated by communities.py)", ""]
for i, mem in enumerate(comms):
    hub = max(mem, key=lambda n: deg.get(n, 0))
    body.append(f"## {i+1}. the **{hub}** community ({len(mem)} nodes)")
    body.append("- " + " · ".join(f"[[{m}]]" if False else m for m in mem))
    body.append("")
isolated = sorted(n for n in nodes if n not in adj)
body.append(f"## Isolated ({len(isolated)}) — no edges yet; connect or justify")
body.append("- " + " · ".join(isolated[:30]))
OUT.write_text("\n".join(body) + "\n", encoding="utf-8")
print(f"communities: {len(comms)} found; colors written; isolated={len(isolated)}")
for i, mem in enumerate(comms[:6]):
    hub = max(mem, key=lambda n: deg.get(n, 0))
    print(f"  {i+1}. {hub}: {', '.join(mem[:8])}{'…' if len(mem) > 8 else ''}")
