#!/usr/bin/env python3
"""register.py — the language/register map (L1 evidence). Sociolinguistics for
the mind: a multilingual speaker's CODE-SWITCHING is structured — which language
he uses maps to relationship domain and register (intimate vs business vs work).
This detects the language of his typed text (heuristic script/marker detection:
Cyrillic->Macedonian, Turkish diacritics, Albanian markers, else English) and
aggregates per app/context over 60 days, with sample utterances per language.
The brain folds the REGISTER structure into MODEL (which language = which world)
and uses it live (a Macedonian burst in WhatsApp = the partner domain; Turkish
in mail = the supplier domain). Output: Atlas/AI/Brain/register.md.
"""
import re, sqlite3
from collections import Counter, defaultdict
from pathlib import Path

DB = Path.home() / "Library/Application Support/2ndMind/brain.db"
OUT = Path.home() / "Projects/2ndm1nd/Atlas/AI/Brain/register.md"
DAYS = 60

TR_STRONG = set("ğşıİĞŞ")
AL_WORDS = re.compile(r"\b(jo|nuk|është|eshte|shkoj|kam|kemi|neser|nesër|heret|mirë|mire|faleminderit|ç'?kemi|po\b|ka\b)\b", re.I)
MK_AL_LATIN = re.compile(r"\b(nema|ajde|te sakam|kako|dobro|blagodaram|vikend|sostanok|utre|sega|sea)\b", re.I)


def detect(text):
    t = text.strip()
    if len(t) < 6:
        return None
    cyr = sum(1 for c in t if "Ѐ" <= c <= "ӿ")
    if cyr > len(t) * 0.25:
        return "MK (Cyrillic)"
    if sum(1 for c in t if c in TR_STRONG) >= 2 or re.search(r"\b(değil|tamam|tmm|şimdi|çok|yarın|olacak|gönder)\b", t, re.I):
        return "TR"
    al = len(AL_WORDS.findall(t))
    mk = len(MK_AL_LATIN.findall(t))
    if al >= 2 and al > mk:
        return "AL"
    if mk >= 2:
        return "MK (Latin)"
    ascii_ratio = sum(1 for c in t if ord(c) < 128) / len(t)
    if ascii_ratio > 0.95:
        return "EN"
    return None


con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True, timeout=5)
rows = con.execute(
    "SELECT COALESCE(app,''), text, date(ts,'unixepoch','localtime')"
    "  FROM events WHERE kind IN ('activity-window','qa-exchange')"
    "   AND text IS NOT NULL AND LENGTH(text) > 15"
    "   AND ts > strftime('%s','now') - ? * 86400", (DAYS,)).fetchall()
con.close()

by_app = defaultdict(Counter)
samples = defaultdict(list)
total = Counter()
for app, text, d in rows:
    if text.startswith("Q: "):                       # qa-exchange: only HIS reply
        m = re.search(r"\nA: (.*)$", text, re.S)
        text = m.group(1) if m else ""
    lang = detect(text)
    if not lang:
        continue
    short_app = app.split(".")[-1] if app else "?"
    by_app[short_app][lang] += 1
    total[lang] += 1
    if lang != "EN" and len(samples[lang]) < 4:
        clip = " ".join(text.split())[:110]
        samples[lang].append(f"{d} [{short_app}] “{clip}”")

body = ["---", "title: register", "type: note", "---", "",
        f"# REGISTER — your language map (L1 evidence, {DAYS}d of typed text; regenerated by register.py)",
        "",
        "Code-switching is structured: which language you type marks which WORLD you're in.",
        "",
        "## Overall (detected utterances)"]
tot = sum(total.values()) or 1
for lang, n in total.most_common():
    body.append(f"- **{lang}** — {n} ({100*n//tot}%)")
body += ["", "## By app (top contexts)"]
for app, cnt in sorted(by_app.items(), key=lambda kv: -sum(kv[1].values()))[:10]:
    mix = " · ".join(f"{l}:{n}" for l, n in cnt.most_common())
    body.append(f"- **{app}** — {mix}")
body += ["", "## Sample utterances (non-EN — the worlds behind the languages)"]
for lang in samples:
    body.append(f"### {lang}")
    body += [f"- {s}" for s in samples[lang]]
OUT.write_text("\n".join(body) + "\n", encoding="utf-8")
print(f"register: {tot} utterances -> {OUT.name}; " + " ".join(f"{l}:{n}" for l, n in total.most_common()))
