#!/usr/bin/env python3
"""rhythm.py — chronotype baseline (L1 evidence). Chronobiology for the mind:
a brain carries an internal model of its own circadian/weekly rhythm, and
salience = deviation from baseline. This computes his ACTUAL rhythm from the
ledger (presence = input+focus events): hour-of-day x weekday activity, the
nightly sleep window, and weekday/weekend shape. The brain folds the baseline
into MODEL (a trait-class claim) and wake cycles read deviations as salient
("active at 03:40 is an anomaly worth noticing; quiet on Sunday morning isn't").
Output: Atlas/AI/Brain/rhythm.md. Deterministic, read-only, ~60-day window.
"""
import sqlite3
from collections import defaultdict
from datetime import date
from pathlib import Path

DB = Path.home() / "Library/Application Support/2ndMind/brain.db"
OUT = Path.home() / "Projects/2ndm1nd/Atlas/AI/Brain/rhythm.md"
DAYS = 60

con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True, timeout=5)
rows = con.execute(
    "SELECT strftime('%w', ts, 'unixepoch', 'localtime') wd,"
    "       strftime('%H', ts, 'unixepoch', 'localtime') h,"
    "       date(ts, 'unixepoch', 'localtime') d, COUNT(*)"
    "  FROM events WHERE source IN ('input','focus')"
    "   AND ts > strftime('%s','now') - ? * 86400 GROUP BY wd, h, d",
    (DAYS,)).fetchall()
con.close()

WD = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
grid = defaultdict(int)              # (wd,h) -> total events
active_days = defaultdict(set)       # (wd,h) -> set of dates active
per_day_hours = defaultdict(set)     # date -> active hours
for wd, h, d, n in rows:
    grid[(int(wd), int(h))] += n
    if n >= 5:
        active_days[(int(wd), int(h))].add(d)
        per_day_hours[d].add(int(h))

ndays = len(per_day_hours)
# presence probability per (wd,h): fraction of that weekday's dates with activity
dates_per_wd = defaultdict(set)
for d in per_day_hours:
    import datetime as _dt
    dates_per_wd[int(_dt.date.fromisoformat(d).strftime("%w"))].add(d)

def prob(wd, h):
    tot = len(dates_per_wd[wd])
    return len(active_days[(wd, h)]) / tot if tot else 0.0

# sleep window: contiguous low-presence hours (avg across all days)
hourly = [sum(prob(w, h) for w in range(7)) / 7 for h in range(24)]
sleep_hours = [h for h in range(24) if hourly[h] < 0.18]
# typical start/end of day
starts = sorted(min(hs) for hs in per_day_hours.values() if hs)
ends = sorted(max(hs) for hs in per_day_hours.values() if hs)
med = lambda xs: xs[len(xs) // 2] if xs else None

body = ["---", "title: rhythm", "type: note", "---", "",
        f"# RHYTHM — your chronotype baseline (L1 evidence, {ndays} active days over {DAYS}d; regenerated by rhythm.py)",
        "",
        f"- Typical day starts (first activity, median): **{med(starts):02d}:00** "
        f"(earliest quartile {starts[len(starts)//4]:02d}:00)" if starts else "- no data",
        f"- Typical day ends (last activity, median): **{med(ends):02d}:00** "
        f"(latest quartile {ends[3*len(ends)//4]:02d}:00)" if ends else "",
        f"- Low-presence hours (presence < 18% of days): "
        f"{', '.join(f'{h:02d}' for h in sleep_hours) or 'none'}",
        "",
        "## Presence probability (fraction of that weekday's days with activity in the hour)",
        "", "| hour | " + " | ".join(WD) + " |", "|---|" + "---|" * 7]
for h in range(24):
    cells = []
    for w in range(7):
        p = prob(w, h)
        cells.append("█" if p > 0.7 else ("▓" if p > 0.4 else ("░" if p > 0.15 else "·")))
    body.append(f"| {h:02d} | " + " | ".join(cells) + " |")
body += ["", "Legend: █ >70% · ▓ >40% · ░ >15% · · rare. Deviation from this grid = salient."]
OUT.write_text("\n".join(body) + "\n", encoding="utf-8")
print(f"rhythm: {ndays} days -> {OUT.name}; day {med(starts):02d}:00-{med(ends):02d}:00, "
      f"low hours {sleep_hours}")
